r= int(input("enter radius of circle"))
print("the area of circle is ", 3.14*r*r)
length = int(input("enter the length of rectangle"))
brdth = int(input("enter the breadth of rectnagle"))
print("the area of reactangle is ",length *brdth)
side = int(input("enter the side of square"))
print("the area of square is", side*side)
h= int(input("enter the height of triangle"))
base= int(input("enter the base of triangle"))
print("the area of triangle is",0.5*h*base)
rad=int(input("enter radius of cylinder1"))
height = int(input("enter the height of cylinder"))
print("the area of cylinder is ",2*3.14*rad*(rad+height))
d1= int(input("enter 1st diagonal of rhombus"))
d2=int(input("enter 2nd diagonal of rhombus"))
z= 0.5*d1*d2
print("the value of first diagonal is {0} & value of sencond diagonal is {1} and the area of rhombus is{2}".format(d1,d2,z))
